logging:
  pattern:
    level: '%5p [${spring.properties.name:},%X{traceId:-},%X{spanId:-}]'


  level:
    org:
      springframework:
        security: DEBUG
server:
  port: 9100
  servlet:
    context-path: /api/v1

spring:
  application:
    name: kotlin_api_rest
  cache:
    cache-names: ticketStatus
    caffeine:
      spec: maximumSize=100, expireAfterWrite=60m
    type: caffeine
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 50
        one-indexed-parameters: false
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 10000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 2
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:mysql://localhost:3306/kotlin_tickets?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME}
  flyway:
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/kotlin_tickets?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC}
    user: ${SPRING_DATASOURCE_USERNAME}
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      fail_on_empty_beans: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${JPA_SHOW_SQL:false}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:9000/api/v1}
          jwk-set-uri: ${JWT_JWK_URI:http://localhost:9000/api/v1/oauth2/jwks}
